/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IHasSecondarySaleFees,
  IHasSecondarySaleFeesInterface,
} from "../IHasSecondarySaleFees";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "id",
        type: "uint256",
      },
    ],
    name: "getFeeBps",
    outputs: [
      {
        internalType: "uint256[]",
        name: "",
        type: "uint256[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "id",
        type: "uint256",
      },
    ],
    name: "getFeeRecipients",
    outputs: [
      {
        internalType: "address payable[]",
        name: "",
        type: "address[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IHasSecondarySaleFees__factory {
  static readonly abi = _abi;
  static createInterface(): IHasSecondarySaleFeesInterface {
    return new utils.Interface(_abi) as IHasSecondarySaleFeesInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IHasSecondarySaleFees {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IHasSecondarySaleFees;
  }
}
