name: test
on:
  # pull_request:
  #   branches: [develop]
  push:
    branches: [main]

  workflow_dispatch: {}

  # push:
  #   branches:    
  #     - develop
  #   tags:
  #     - 'test-v[0-9]+.[0-9]+.[0-9]+'
jobs:
  test:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - run: echo "this is test"
      - run: |
          echo "${GITHUB_REF#refs/heads/}" | tr '._/' '-'
      - run: |
          echo "${REF##*/}"
      - run: |
          echo ${{ github.ref }}
