name: test
on:
  pull_request:
    branches: [develop]
  workflow_dispatch: {}
  # push:
  #   branches:    
  #     - develop
  #   tags:
  #     - 'test-v[0-9]+.[0-9]+.[0-9]+'
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - run: echo "this is test"
      - run: |
          echo "${GITHUB_REF#refs/heads/}" | tr '._/' '-'
      - run: |
          echo "${${REF##*/}}"
      - run: |
          echo ${{ github.ref }}
