name: test
on:
  push:
    branches:    
      - develop
    tags:
      - 'test-v[0-9]+.[0-9]+.[0-9]+'
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - run: echo "this is test"
